# Generated by Django 4.1.7 on 2023-04-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
