# Generated by Django 4.1.7 on 2023-04-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cartproduct_remain_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_staus',
            field=models.CharField(choices=[('Ordering', 'Ordering'), ('Delivered', 'Delivered'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('Consignment', 'Consignment'), ('Complete', 'Complete')], default='Ordering', max_length=255),
        ),
    ]
