# Generated by Django 4.1.7 on 2023-04-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_created_at_alter_order_ordered_staus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
            ],
        ),
    ]
