# Generated by Django 4.1.7 on 2023-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=225)),
                ('item_name', models.CharField(max_length=225)),
                ('purchase_qty', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('p_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
