# Generated by Django 4.1.7 on 2023-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_expenseledger_expensereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('item_code', models.CharField(max_length=225)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=225)),
                ('return_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
