# Generated by Django 4.1.7 on 2023-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_damageitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageitems',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='damageitems',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='damageitems',
            name='item_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
