# Generated by Django 4.1.7 on 2023-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_damageitems_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='total_purchase_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_staus',
            field=models.CharField(choices=[('Ordering', 'Ordering'), ('Delivered', 'Delivered'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('Consignment', 'Consignment'), ('Complete', 'Complete')], default='Cash', max_length=255),
        ),
    ]
