# Generated by Django 4.1.7 on 2023-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cartproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
