# Generated by Django 4.1.7 on 2023-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_items_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
