# Generated by Django 4.1.7 on 2023-04-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_items_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.deliverysystem'),
            preserve_default=False,
        ),
    ]
