# Generated by Django 4.1.7 on 2023-04-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_deliverysystem_order_delivery_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.deliverysystem'),
        ),
    ]
