# Generated by Django 4.1.7 on 2023-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_order_delivery_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('COD', 'COD'), ('Kpay', 'Kpay'), ('WavePay', 'WavePay')], default='Cash', max_length=225),
        ),
    ]
