# Generated by Django 4.1.7 on 2023-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deli_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
