# Generated by Django 4.1.7 on 2023-04-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order_deli_payment_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='logistic',
            field=models.IntegerField(default=0),
        ),
    ]
