# Generated by Django 5.0 on 2024-01-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_ecommercebanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommerceorder',
            old_name='ordered_by',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ecommerceorder',
            name='all_total',
        ),
        migrations.RemoveField(
            model_name='ecommerceorder',
            name='all_total_delivery',
        ),
        migrations.RemoveField(
            model_name='ecommerceorder',
            name='ordered_staus',
        ),
        migrations.RemoveField(
            model_name='ecommerceorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='ecommerceorder',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='ecommerceorder',
            name='total',
        ),
    ]
