# Generated by Django 5.0 on 2024-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_ecommerceorder_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itm_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
