# Generated by Django 5.0 on 2024-01-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_messengerid_messengerbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerbot',
            name='messengerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.messengerid'),
        ),
    ]
