# Generated by Django 5.0 on 2024-01-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_messengerbot_messengerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
