# Generated by Django 5.0 on 2024-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_messengerid_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerbot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
