# Generated by Django 5.0 on 2024-02-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_messengerbot_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
