# Generated by Django 5.0 on 2024-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_itmcolor_itmsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
